// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetElectionsWinUI.Data;

#nullable disable

namespace ProjetElectionsWinUI.Data.Migrations
{
    [DbContext(typeof(ElectionsContext))]
    [Migration("20251127050325_MigrationInitiale")]
    partial class MigrationInitiale
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("ProjetElectionsWinUI.Data.Models.DistrictElectoral", b =>
                {
                    b.Property<int>("DistrictElectoralId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomDistrict")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Population")
                        .HasColumnType("INTEGER");

                    b.HasKey("DistrictElectoralId");

                    b.ToTable("Districts");

                    b.HasData(
                        new
                        {
                            DistrictElectoralId = 1,
                            NomDistrict = "Hull",
                            Population = 72000
                        },
                        new
                        {
                            DistrictElectoralId = 2,
                            NomDistrict = "Gatineau",
                            Population = 290000
                        },
                        new
                        {
                            DistrictElectoralId = 3,
                            NomDistrict = "Aylmer",
                            Population = 45000
                        });
                });

            modelBuilder.Entity("ProjetElectionsWinUi.Data.Models.Candidat", b =>
                {
                    b.Property<int>("CandidatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DistrictElectoralId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PartiPolitique")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VotesObtenus")
                        .HasColumnType("INTEGER");

                    b.HasKey("CandidatId");

                    b.HasIndex("DistrictElectoralId");

                    b.ToTable("Candidats");

                    b.HasData(
                        new
                        {
                            CandidatId = 1,
                            DistrictElectoralId = 1,
                            Nom = "Maude Marquis-Bissonnette",
                            PartiPolitique = "Action Gatineau",
                            VotesObtenus = 0
                        },
                        new
                        {
                            CandidatId = 2,
                            DistrictElectoralId = 2,
                            Nom = "Mario Aubé",
                            PartiPolitique = "Équipe Mario Aubé",
                            VotesObtenus = 0
                        },
                        new
                        {
                            CandidatId = 3,
                            DistrictElectoralId = 3,
                            Nom = "Rémi Bergeron",
                            PartiPolitique = "Indépendant",
                            VotesObtenus = 0
                        });
                });

            modelBuilder.Entity("ProjetElectionsWinUi.Data.Models.Electeur", b =>
                {
                    b.Property<int>("ElecteurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("TEXT");

                    b.Property<int>("DistrictElectoralId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ElecteurId");

                    b.HasIndex("DistrictElectoralId");

                    b.ToTable("Electeurs");

                    b.HasData(
                        new
                        {
                            ElecteurId = 1,
                            Adresse = "123 Rue Principale",
                            DateNaissance = new DateTime(1990, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DistrictElectoralId = 1,
                            Nom = "Martin Dupont"
                        },
                        new
                        {
                            ElecteurId = 2,
                            Adresse = "456 Avenue du Lac",
                            DateNaissance = new DateTime(1985, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DistrictElectoralId = 2,
                            Nom = "Julie Tremblay"
                        },
                        new
                        {
                            ElecteurId = 3,
                            Adresse = "789 Boulevard des Allumettières",
                            DateNaissance = new DateTime(2000, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DistrictElectoralId = 3,
                            Nom = "Karim Bennani"
                        });
                });

            modelBuilder.Entity("ProjetElectionsWinUi.Data.Models.Candidat", b =>
                {
                    b.HasOne("ProjetElectionsWinUI.Data.Models.DistrictElectoral", "District")
                        .WithMany("Candidats")
                        .HasForeignKey("DistrictElectoralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("ProjetElectionsWinUi.Data.Models.Electeur", b =>
                {
                    b.HasOne("ProjetElectionsWinUI.Data.Models.DistrictElectoral", "District")
                        .WithMany("Electeurs")
                        .HasForeignKey("DistrictElectoralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("ProjetElectionsWinUI.Data.Models.DistrictElectoral", b =>
                {
                    b.Navigation("Candidats");

                    b.Navigation("Electeurs");
                });
#pragma warning restore 612, 618
        }
    }
}
